spring.application.name=focusforge-backend
app.admin.email=admin.focusforge@gmail.com


spring.datasource.url=jdbc:postgresql://ep-long-dust-a1wlw2dh-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dbhsz6wHtU7Q